# Generated by Django 4.2.9 on 2024-02-02 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedGif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gif_path', models.CharField(max_length=255)),
                ('entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Birthday.entry')),
            ],
        ),
    ]
