# Generated by Django 4.2.9 on 2024-02-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0002_selectedgif'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='selected_gif',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='SelectedGif',
        ),
    ]
