# Generated by Django 4.2.9 on 2024-02-05 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Birthday', '0003_entry_selected_gif_delete_selectedgif'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='point_X',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='point_Y',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='selected_gif',
            field=models.CharField(max_length=255),
        ),
    ]
